[app]
name = "RHEX"

[key]
length = 20
master_key_length = 10

# Output password configuration.

lowercase_letters = true
uppercase_letters = false
special_characters = false
figures = true

[encryption]
encryption_mode = "gcm"

[advanced_settings]
security_mode = true
delete_all_operation_sleep_time = 0
list_all_operation_sleep_time = 0
add_key_sleep_time = 0

[argon2]
time_cost = 5
memory_cost = 262144
parallelism = 4
hash_len = 32
salt_len = 16